name: PullRequestAction

on:
  # push:
  #   branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Initialise environment
        run: cat ".github-env-$GITHUB_BASE_REF" >> $GITHUB_ENV

      - name: Pull PR repo and merge with original branch
        run: /srv/github-action-scripts/merge-test-branch.sh
      
      - name: Build site
        run: /srv/github-action-scripts/build-jekyll-site.sh
